  apiVersion: apps/v1
  kind: Deployment  
  metadata:  
    name: app-deployment  
  spec:      
      selector:
        matchLabels:
          app: app-deployment
      template:
        metadata:  
          labels:  
            app: app-deployment
        spec:  
          containers:  
            - name: app-deployment-container  
              image: fabricioveronez/corecrud:v2 
              ports:  
                - containerPort: 80
                - containerPort: 8080